name: scalable_test
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  #flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^4.0.1
  flutter_bloc: ^8.0.1
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.13.0
  mocktail: ^0.3.0
  bloc_test: ^9.0.3

dev_dependencies:
  flutter_lints: ^2.0.1
